### ISSUE TITLE
Staged submodules cause run failure

### ISSUE THREAD

**Issue by apiology** [pclalv/pronto-shellcheck#4]
## How to reproduce

Create uncommited submodule changes in a project and run pronto with pronto-shellcheck installed.

Example:

```
mkdir new-project
cd new-project
git init
 echo 'hello world' > README.md
git add README.md
git commit -m "First commit"
git submodule add https://github.com/pclalv/pronto-shellcheck
gem install pronto pronto-shellcheck
pronto run --staged
```

## Expected result

No errors on run.

## Actual results

```
]0;macmicrobroz@macmicro:~/src/new-project$ pronto run --staged
pronto run --staged
/Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:37:in `readlines': Is a directory @ io_fillbuf - fd:9 /Users/broz/src/new-project/pronto-shellcheck (Errno::EISDIR)
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:37:in `file_has_shebang?'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:29:in `shellcheckable?'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:23:in `block in run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/git/patches.rb:15:in `each'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/git/patches.rb:15:in `each'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:23:in `select'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-shellcheck-0.1.2/lib/pronto/shellcheck_runner.rb:23:in `run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/runners.rb:20:in `block in run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `each'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto.rb:64:in `run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/broz/.rvm/gems/ruby-2.3.1/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /Users/broz/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
	from /Users/broz/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
	from /Users/broz/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/broz/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
]0;macmicrobroz@macmicro:~/src/new-project$ 
```

**Comment by pclalv** [comment]
@apiology i just pushed the latests build of the gem to rubygems. sorry for the delay.

**Comment by apiology** [comment]
Thanks!
